#!/bin/bash
set -e

BASE_DIR=`cd "$(dirname "$0")";pwd`
cd "$BASE_DIR"

RELATIVE_DIR=`dirname "$0"`

for f in $(find scripts -type f)
do
  ln -sf "$RELATIVE_DIR/scripts/`basename "$f"`" "$OLDPWD"/
done
