#!/bin/bash
set -e

BASE_DIR=`cd "$(dirname "$0")";pwd`
cd "$BASE_DIR"

for f in $(find scripts -type f)
do
  f=${f##scripts/}
  d=`dirname $f`
  mkdir -p "$OLDPWD/$d"
  ln -sf "$BASE_DIR/scripts/$f" "$OLDPWD"/$d/
done
