= JBoss Scripts
:toc:
:numbered:

This project is a small bunch of https://www.gnu.org/software/bash/[Bash] scripts intended to facilitate <<tasks,tasks>> with different versions of JBoss (including http://wildfly.org[Wildfly], https://developers.redhat.com/products/eap/overview/[EAP], and older) installed through zips.

== JBoss versions already tested with this scripts

* JBoss EAP 7
* JBoss EAP 6
* JBoss EAP 5

== Installation

Go to a directory where you already downloaded binaries for a specific JBoss version. For example, supose that you are in a directory called `jboss-eap-7` with this structure:

----
$ cd jboss-eap-7
$ find .
.
./jboss-eap-7.0.0-maven-repository.zip
./jboss-eap-7.0.0-quickstarts.zip
./jboss-eap-7.0.0.zip
./jboss-eap-7.0.4-incremental-maven-repository.zip
./jboss-eap-7.0.4-patch.zip
./jboss-eap-7.0.4-src.zip
----

To start using `jboss-scripts` with this version of jboss, do this:

----
$ (cd .. && git clone https://github.com/paulojeronimo/jboss-scripts)
$ ../jboss-scripts/install
----

You will see that some links were created:

----
$ find . -type l|sort|xargs readlink
../jboss-scripts/scripts/home
../jboss-scripts/scripts/jboss-config.sample
../jboss-scripts/scripts/jboss-deploy
../jboss-scripts/scripts/jboss-install
../jboss-scripts/scripts/jboss-run
../jboss-scripts/scripts/jboss-undeploy
----

== Uninstallation

----
$ ../jboss-scripts/uninstall
----

== Configuration

Inside link:scripts[] directory, copy link:scripts/jboss-config.sample[jboss-config.sample] to `jboss-config` and edit it according to your needs.

You can also create a file named `jboss-version`. Inside it, configure a `$JBOSS_VERSION`. For example, if you are configuring a JBoss EAP 6.4 dir, you can do:

----
$ pwd
jboss-eap-6
$ echo "JBOSS_VERSION=6.4" > jboss-version
----

If you created this file, it will be sourced before `jboss-config`. So, you can take some configure decisions based on `$JBOSS_VERSION` value.

[[tasks]]
== Tasks

=== Configure your PATH and put JBOSS variables in your shell

To configure your `PATH` and put all `JBOSS_` variables visible in your shell, execute:

----
$ ./source home
----

[TIP]
====
You could run `source <script>` from anywhere.
====

Now, you can see the what `JBOSS_` variables are present:

----
$ echo ${!JBOSS_*}|tr ' ' '\n'
----

=== Install JBoss

To install JBoss (removing the existing installation), execute:

----
jboss-install
----

The link:scripts/jboss-install[jboss-install] script will do many tasks. For example, it will:

. Extract the (default or configured) JBoss zip installer.
. Apply the configured patches.
. Configure modules and JDBC drivers (ex: Oracle).
. Create a configured JBoss zip installer.

[TIP]
====
The `jboss-install` script will extract the configured JBoss zip installer (if it exists). You can force a creation of this zip running `jboss-install -f`.
====

=== Run JBoss

To run JBoss:

----
jboss-run
----

=== Deploy a package

To deploy a package (copying it to `$JBOSS_HOME/$JBOSS_DEPLOY_DIR`):

----
jboss-deploy package
----

=== Undeploy a package

To undeploy a package (removing it from `$JBOSS_HOME/$JBOSS_DEPLOY_DIR`):

----
jboss-undeploy package
----
