#!/bin/bash
set -e

BASE_DIR=`cd "$(dirname "$0")";pwd`
cd "$BASE_DIR"

for f in $(find scripts -type f)
do
  f=${f##scripts/}
  d=`dirname $f`
  rm -f $OLDPWD/$f
  [ "$d" != '.' ] && { _ls=$(ls -A $OLDPWD/$d 2> /dev/null) && { [ "$_ls" ] || rmdir "$OLDPWD/$d"; }; }
done
