#!/bin/bash

version="$BASE_DIR"/jboss-version
if [ -r "$version" ]
then
  echo "Loading JBoss version configuration from \"$version\" ..."
  source "$version"
fi

config="$BASE_DIR"/jboss-config
load_configuration_warned=${load_configuration_warned:-false}
[ -r "$config" ] || config=$config.sample
$load_configuration_warned || {
  echo "Loading JBoss configurations from \"$config\" ..."
  export load_configuration_warned=true
}
source "$config"
