#!/bin/bash
set -e

if ! (( `id -u` == 0 ))
then
  echo "You must be run this script with sudo (or as root)!"
  exit
fi

BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

cd "$BASE_DIR"

if grep -q $JBOSS_GROUP /etc/group
then
  groupdel $JBOSS_GROUP && echo "JBOSS_GROUP ($JBOSS_GROUP) removed!"
else
  echo "JBOSS_GROUP ($JBOSS_GROUP) already removed!"
fi
