#!/bin/bash
set -e

if ! (( `id -u` == 0 ))
then
  echo "You must be run this script with sudo (or as root)!"
  exit
fi

BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

op="$1"
shift || true
case "$op" in
  install)
    "$BASE_DIR"/jboss-install-as-a-service "$@"
    ;;
  start|status|stop|enable|disable)
    systemctl $JBOSS_NAME $op
esac
