#!/bin/bash
set -e

BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

cd "$BASE_DIR"

sed_i() { 
  case $OSTYPE in
    linux*|cygwin) sed -i "$@";;
    darwin*) sed -i '' "$@";;
  esac
}

jboss-cli() {
  $JBOSS_DIR/bin/jboss-cli.sh "$@" > /dev/null
}

check-configured-zip() {
  JBOSS_CONFIGURED=false

  if [ "$1" = "-f" ]
  then
    echo "Removing configured JBoss ($JBOSS_CONFIGURED_ZIP) ..."
    rm -f $JBOSS_CONFIGURED_ZIP
  fi

  if [ -f $JBOSS_CONFIGURED_ZIP ]
  then
    JBOSS_ZIP=$JBOSS_CONFIGURED_ZIP
    JBOSS_CONFIGURED=true
  fi
}

remove-existing() {
  if [ -d "$JBOSS_DIR" ]
  then
    echo "Removing existing installation ($JBOSS_DIR) ..."
    rm -rf "$JBOSS_DIR"
  fi
}

extract-new() {
  echo "Extracting \"$JBOSS_ZIP\" ..."
  unzip -q "$JBOSS_ZIP"
}

add-user() {
  case "$JBOSS_VERSION" in
    5*)
      echo "TODO: implement add-user for JBoss version $JBOSS_VERSION"
      return
      ;;
  esac

  echo "  Adding JBoss admin user ($JBOSS_ADMIN_USER) ..."
  $JBOSS_DIR/bin/add-user.sh -s -u "$JBOSS_ADMIN_USER" -p "$JBOSS_ADMIN_PASSWORD"
}

add-user-keycloak() {
  if [ "$JBOSS_NAME" =  "rh-sso" ]
  then
    echo "  Adding RH-SSO admin user ($RH_SSO_ADMIN_USER) ..."
    $JBOSS_DIR/bin/add-user-keycloak.sh -u "$RH_SSO_ADMIN_USER" -p "$RH_SSO_ADMIN_PASSWORD" > /dev/null
  fi
}

extract-native-components() {
  if [ "$JBOSS_VERSION" = "6.4" -a -r "$JBOSS_NATIVE_COMPONENTS_ZIP" ]
  then
    echo "  Extracting native components (\"$JBOSS_NATIVE_COMPONENTS_ZIP\")..."
    unzip -q $JBOSS_NATIVE_COMPONENTS_ZIP

    echo '  TODO: Using the Management CLI, activate the native components:'
    echo '/subsystem=web:write-attribute(name=native,value=true)"'
  fi
}

apply-jboss-patches() {
  if [ "${JBOSS_PATCHES[*]}" ]
  then
    echo "  Applying JBoss patches ..."
  else
    echo "  JBOSS_PATCHES array not configured! Skipping patches ..."
    return
  fi

  local n
  for n in `seq ${#JBOSS_PATCHES[*]}`
  do
    local patch=${JBOSS_PATCHES[$n]}
    echo "    Applying $patch ..."
    jboss-cli --command="patch apply --override-all $patch"
  done
}

apply-user-patches() {
  local patch_sufix=".patch"
  local f
  local patches_dir=`dirname "$(readlink "$0")"`/../patches/$JBOSS_DIR

  if [ -d "$patches_dir" ]
  then
    patches_dir=`cd "$patches_dir"; pwd`
  else
    echo "  user-patches not found (in $patches_dir)! Skipping patches ..."
    return
  fi

  echo "  Applying user patches (from \"$patches_dir\")..."

  cd "$patches_dir"
  echo "    Copying patches to $JBOSS_DIR ..."
  rsync -a . "$BASE_DIR"/$JBOSS_DIR/
  cd - &> /dev/null

  for f in $(find $JBOSS_DIR -name \*$patch_sufix)
  do
    echo "    Saving ${f%$patch_sufix} with \".original\" extension ..."
    cp ${f%$patch_sufix} ${f%$patch_sufix}.original
    echo "    Applying $f ..."
    patch ${f%$patch_sufix} < $BASE_DIR/$f > /dev/null
  done
}

configure-jboss-variables() {
  local f=$JBOSS_DIR/bin/standalone.conf

  echo "  Setting jboss variables in $f ..."
  sed_i "
    s/JBOSS_BIND_ADDRESS_MANAGEMENT/$JBOSS_BIND_ADDRESS_MANAGEMENT/g ;
    s/JBOSS_BIND_ADDRESS/$JBOSS_BIND_ADDRESS/g ;
    s/JBOSS_SOCKET_BINDING_PORT_OFFSET/$JBOSS_SOCKET_BINDING_PORT_OFFSET/g
  " $f

  echo "    JBOSS_BIND_ADDRESS_MANAGEMENT=$JBOSS_BIND_ADDRESS_MANAGEMENT"
  echo "    JBOSS_BIND_ADDRESS=$JBOSS_BIND_ADDRESS"
  echo "    JBOSS_SOCKET_BINDING_PORT_OFFSET=$JBOSS_SOCKET_BINDING_PORT_OFFSET"
}

install-oracle-jdbc-driver() {
  if ! $ORACLE_JDBC_DRIVER_INSTALL
  then
    return 0
  else
    if ! [ -f "$ORACLE_JDBC_DRIVER" ]
    then
      echo "  Can't find \"$ORACLE_JDBC_DRIVER\". Please verify your configuration!"
      return 1
    fi
  fi

  local cli=/tmp/oracle-module.cli

  cat > $cli <<EOF
module add \
--name=oracle.jdbc \
--resources=$ORACLE_JDBC_DRIVER \
--dependencies=javax.api,javax.transaction.api
EOF
  echo "  Installing oracle.jdbc module ..."
  rm -rf "$JBOSS_DIR"/modules/system/layers/base/oracle/
  jboss-cli --file=$cli
  mv "$JBOSS_DIR"/modules/oracle "$JBOSS_DIR"/modules/system/layers/base/

  echo "  Adding oracle jdbc driver ..."

  cli="$BASE_DIR"/cli/add-oracle-driver.cli
  echo "    Running \"$cli\" with jboss-cli ..."
  if [ -f "$cli" ]
  then
    jboss-cli --file=$cli
  else
    echo "      File not found!"
    return 1
  fi
}

install-rh-sso-adapter() {
  if ! $RH_SSO_ADAPTER_INSTALL
  then
    return 0
  fi

  echo "  Installing RH-SSO client adapter ..."
  echo "    Extracting \"$RH_SSO_ADAPTER_ZIP\" ..."
  unzip -q "$RH_SSO_ADAPTER_ZIP" -d "$JBOSS_DIR"

  local cli="$JBOSS_DIR"/bin/adapter-install-offline.cli
  echo "    Running \"$cli\" with jboss-cli ..."
  if [ -f "$cli" ]
  then
    jboss-cli --file=$cli
  else
    echo "      File not found!"
    return 1
  fi
}

configure-https() {
  if ! $JBOSS_EAP_HTTPS_INSTALL
  then
    return 0
  fi

  echo "  Configuring HTTPS access ..."

  local keystore=keystore.jks  
  echo "    Generating $keystore ..."
  keytool -genkey -noprompt -alias $JBOSS_BIND_ADDRESS \
    -keyalg RSA -keystore $keystore -validity 10950 \
    -dname "CN=$JBOSS_BIND_ADDRESS, OU=$JBOSS_NAME, O=test, L=Rio, ST=RJ, C=BR" \
    -storepass secret -keypass secret
  mv $keystore $JBOSS_DIR/standalone/configuration

  local cli="$BASE_DIR"/cli/configure-https.cli
  echo "    Running \"$cli\" with jboss-cli ..."
  if [ -f "$cli" ]
  then
    jboss-cli --file=$cli
  else
    echo "      File not found!"
    return 1
  fi
}

create-configured-zip() {
  case "$JBOSS_VERSION" in
    5*)
      echo "TODO: implement create-configured-zip for JBoss version $JBOSS_VERSION"
      return
      ;;
  esac

  if ! $JBOSS_CONFIGURED
  then
    echo "Creating \"$JBOSS_CONFIGURED_ZIP\" ..."
    add-user
    add-user-keycloak
    apply-jboss-patches
    # INFO: native components must be installed after applying jboss patches, otherwise it fails!
    extract-native-components
    apply-user-patches
    configure-jboss-variables
    install-oracle-jdbc-driver
    install-rh-sso-adapter
    configure-https
    echo "  Creating zip ..."
    zip -qr $JBOSS_CONFIGURED_ZIP $JBOSS_DIR
  fi
}

check-configured-zip "$@"
remove-existing
extract-new
create-configured-zip
