#!/bin/bash
set -e

if ! (( `id -u` == 0 ))
then
  echo "You must be run this script with sudo (or as root)!"
  exit
fi

BASE_DIR=`cd "$(dirname "$0")"; pwd`
source "$BASE_DIR"/common

cd "$BASE_DIR"

[ "$SUDO_USER" ] && using_sudo=true || using_sudo=false
[ -d "$JBOSS_DIR" -a -f "$JBOSS_CONFIGURED_ZIP" ] || { 
  $using_sudo \
    && sudo -u $SUDO_USER ./jboss-install \
    || ./jboss-install;
}

echo "Removing \"$JBOSS_INSTALL_DIR/$JBOSS_DIR\" ..."
cd "$JBOSS_INSTALL_DIR" && { rm -rf "$JBOSS_DIR"; cd - > /dev/null; }

echo "Extracting \"$JBOSS_CONFIGURED_ZIP\" to \"$JBOSS_INSTALL_DIR\" ..."
unzip -q -d "$JBOSS_INSTALL_DIR" "$JBOSS_CONFIGURED_ZIP"

echo "Creating link $JBOSS_NAME on $JBOSS_INSTALL_DIR ..."
ln -sf "$JBOSS_INSTALL_DIR/$JBOSS_DIR" "$JBOSS_INSTALL_DIR/$JBOSS_NAME"

grep -q $JBOSS_USER /etc/passwd || ./jboss-useradd

echo "Configuring owner ($JBOSS_USER:$JBOSS_GROUP) for dir \"$JBOSS_INSTALL_DIR/$JBOSS_DIR\" ..."
chown -R $JBOSS_USER:$JBOSS_GROUP "$JBOSS_INSTALL_DIR/$JBOSS_DIR"

f=/usr/lib/systemd/system/rh-sso.service
echo "Creating \"$f\":"
cat > $f <<EOF
[Unit]
Description=RH-SSO 7.1 Systemctl script
After=NetworkManager.service

[Service]
Type=forking
ExecStart=$JBOSS_INSTALL_DIR/$JBOSS_DIR/bin/init.d/jboss-eap-rhel.sh start
ExecStop=$JBOSS_INSTALL_DIR/$JBOSS_DIR/bin/init.d/jboss-eap-rhel.sh stop
ExecReload=$JBOSS_INSTALL_DIR/$JBOSS_DIR/bin/init.d/jboss-eap-rhel.sh restart
Environment="JBOSS_NAME=$JBOSS_NAME"
Environment="JBOSS_USER=$JBOSS_USER"
PIDFile=/var/run/jboss-eap/$JBOSS_NAME.pid

[Install]
WantedBy=multi-user.target
EOF
cat -n $f

echo "Reloading systemctl daemon ..."
systemctl daemon-reload
