#!/bin/bash
set -e

BASE_DIR=`cd "$(dirname "$0")"; pwd`
cd "$BASE_DIR"

[ -r version ] && source version || true
config=config
[ -r "$config" ] || config=config.sample
source $config

sed_i() { 
  case $OSTYPE in
    linux*|cygwin) sed -i "$@";;
    darwin*) sed -i '' "$@";;
  esac
}

check-configured-zip() {
  JBOSS_CONFIGURED=false
  JBOSS_CONFIGURED_ZIP=`basename $JBOSS_ZIP .zip`.configured.zip

  if [ "$1" = "-f" ]
  then
    echo "Removing configured JBoss ($JBOSS_CONFIGURED_ZIP) ..."
    rm -f $JBOSS_CONFIGURED_ZIP
  fi

  if [ -f $JBOSS_CONFIGURED_ZIP ]
  then
    JBOSS_ZIP=$JBOSS_CONFIGURED_ZIP
    JBOSS_CONFIGURED=true
  fi
}

remove-existing() {
  if [ -d "$JBOSS_DIR" ]
  then
    echo "Removing existing installation ($JBOSS_DIR) ..."
    rm -rf "$JBOSS_DIR"
  fi
}

extract-new() {
  echo "Extracting \"$JBOSS_ZIP\" ..."
  unzip -q "$JBOSS_ZIP"
}

add-user() {
  case "$JBOSS_VERSION" in
    5*)
      echo "TODO: implement add-user for JBoss version $JBOSS_VERSION"
      return
      ;;
  esac

  echo "  Adding JBoss admin user ($JBOSS_ADMIN_USER) ..."
  $JBOSS_DIR/bin/add-user.sh -s -u "$JBOSS_ADMIN_USER" -p "$JBOSS_ADMIN_PASSWORD"
}

extract-native-components() {
  if [ "$JBOSS_VERSION" = "6.4" -a -r "$JBOSS_NATIVE_COMPONENTS_ZIP" ]
  then
    echo "  Extracting native components (\"$JBOSS_NATIVE_COMPONENTS_ZIP\")..."
    unzip -q $JBOSS_NATIVE_COMPONENTS_ZIP

    echo '  TODO: Using the Management CLI, activate the native components:'
    echo '/subsystem=web:write-attribute(name=native,value=true)"'
  fi
}

apply-jboss-patches() {
  if ! [ "${JBOSS_PATCHES[*]}" ]
  then
    echo "  JBOSS_PATCHES array not configured!"
    exit 1
  fi
  echo "  Applying JBoss patches ..."

  local n
  for n in `seq ${#JBOSS_PATCHES[*]}`
  do
    local patch=${JBOSS_PATCHES[$n]}
    echo "    Applying $patch ..."
    $JBOSS_DIR/bin/jboss-cli.sh --command="patch apply --override-all $patch" > /dev/null
  done
}

apply-user-patches() {
  local patch_sufix=".patch"
  local f
  local patches_dir=`dirname "$(readlink "$0")"`/../patches/$JBOSS_DIR

  if [ -d "$patches_dir" ]
  then
    patches_dir=`cd "$patches_dir"; pwd`
  else
    return
  fi

  echo "  Applying user patches (from \"$patches_dir\")..."

  cd "$patches_dir"
  echo "    Copying patches to $JBOSS_DIR ..."
  rsync -a . "$BASE_DIR"/$JBOSS_DIR/
  cd - &> /dev/null

  for f in $(find $JBOSS_DIR -name \*$patch_sufix)
  do
    echo "    Saving ${f%$patch_sufix} with \".original\" extension ..."
    cp ${f%$patch_sufix} ${f%$patch_sufix}.original
    echo "    Applying $f ..."
    patch ${f%$patch_sufix} < $BASE_DIR/$f > /dev/null
  done
}

configure-jboss-variables() {
  local f=$JBOSS_DIR/bin/standalone.conf

  echo "  Setting JBOSS_BIND_ADDRESS_MANAGEMENT ($JBOSS_BIND_ADDRESS_MANAGEMENT) in $f ..."
  sed_i "s/JBOSS_BIND_ADDRESS_MANAGEMENT/$JBOSS_BIND_ADDRESS_MANAGEMENT/g" $f

  echo "  Setting JBOSS_BIND_ADDRESS ($JBOSS_BIND_ADDRESS) in $f ..."
  sed_i "s/JBOSS_BIND_ADDRESS/$JBOSS_BIND_ADDRESS/g" $f
}

create-configured-zip() {
  case "$JBOSS_VERSION" in
    5*)
      echo "TODO: implement create-configured-zip for JBoss version $JBOSS_VERSION"
      return
      ;;
  esac

  if ! $JBOSS_CONFIGURED
  then
    echo "Creating \"$JBOSS_CONFIGURED_ZIP\" ..."
    add-user
    apply-jboss-patches
    # INFO: native components must be installed after applying jboss patches, otherwise it fails!
    extract-native-components
    apply-user-patches
    configure-jboss-variables
    echo "  Creating zip ..."
    zip -qr $JBOSS_CONFIGURED_ZIP $JBOSS_DIR
  fi
}

check-configured-zip "$@"
remove-existing
extract-new
create-configured-zip
